# Generated by Django 5.1.7 on 2025-03-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_evstation_total_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('available', 'Available'), ('cancelled', 'Cancelled')], default='booked', max_length=20),
        ),
    ]
